# Use a imagem oficial do Nginx como base
FROM nginx:latest

# Copie o arquivo de configuração personalizado para o contêiner
COPY app.conf /etc/nginx/conf.d/

# Copie os arquivos da aplicação React para o diretório padrão do Nginx
COPY . /usr/share/nginx/html

# Exponha a porta 8080
EXPOSE 8080

# Inicie o Nginx em primeiro plano
CMD ["nginx", "-g", "daemon off;"]